version: '3.7'
services:
  vintage_1:
    image: vintage:latest
    restart: always
    ports:
      - "8001:8001"
    environment:
      - RUST_LOG=info
    command: vintage -c /vintage/config.yml
    depends_on:
      - cache_1
      - db_1
    
  dtomcat_1:
    image: dtomcat:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=cache_1:6379
      - DB_HOST=db_1:5432
      - REDIS_URL=redis://cache_1:6379
      - DB_URL=postgresql://postgres:postgres@db_1:5432/#proto?sslmode=disable
      - RUST_LOG=info
    command: dtomcat
    depends_on:
      - cache_1
      - db_1
      - vintage_1

  db_1:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=${POSTGRES_DBNAME}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes: 
      # - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./init_pg.sql:/docker-entrypoint-initdb.d/init_pg.sql
    depends_on:
      - cache_1

  cache_1:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning 
    #volumes: 
      # - cache:/data

